--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/DailyRewardsPE
build-by-default: true
branches:
- main
projects:
  DailyRewardsPE:
    path: “”
    lint:
      phpstan: false
...
