name: DailyRewardsPM
version: 1.0.0
author: KnosTx
api: 5.0.0
main: KnosTx\DailyRewardsPM\Main
description: A DailyRewardsPM plugin for Pocketmine-MP.

permissions:
  dailyrewardspm.command.daily:
    description: Daily Rewards.
    default: true
  dailyrewardspm.command.weekly:
    description: Weekly Rewards.
    default: true
  dailyrewardspm.command.monthly:
    description: Monthly Rewards.
    default: true
